language: node_js
node_js:
  - 12

install:
  - npm install

script:
  - npm test

notifications:
  email:
    recipients:
      - lav@yoctu.com

deploy:
  provider: npm
  email: "lav@yoctu.com"
  api_key: $NPM_KEY
  edge: true
  on:
    branch: master
